"""Initial

Revision ID: 035c54de2fe0
Revises: 693095caf62b
Create Date: 2025-02-18 02:44:36.087622

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "035c54de2fe0"
down_revision: Union[str, None] = "693095caf62b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
