"""empty message

Revision ID: 693095caf62b
Revises:
Create Date: 2025-02-17 21:48:33.302203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "693095caf62b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kanban_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("assignee", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("due_date", sa.String(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("cooldown", sa.String(), nullable=False),
        sa.Column("history_as_string", sa.String(), nullable=False),
        sa.Column("days_till_todo", sa.Integer(), nullable=False),
        sa.Column("hours_till_todo", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kanban_cards_id"), "kanban_cards", ["id"], unique=False)
    op.create_table(
        "history_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["kanban_cards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_history_records_id"), "history_records", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_history_records_id"), table_name="history_records")
    op.drop_table("history_records")
    op.drop_index(op.f("ix_kanban_cards_id"), table_name="kanban_cards")
    op.drop_table("kanban_cards")
    # ### end Alembic commands ###
