"""empty message

Revision ID: 6bd4658c1c25
Revises: 035c54de2fe0
Create Date: 2025-03-02 18:10:21.136741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bd4658c1c25"
down_revision: Union[str, None] = "035c54de2fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.add_column("kanban_cards", sa.Column("assignee_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "kanban_cards", "users", ["assignee_id"], ["id"])
    op.drop_column("kanban_cards", "assignee")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kanban_cards", sa.Column("assignee", sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, "kanban_cards", type_="foreignkey")
    op.drop_column("kanban_cards", "assignee_id")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
